### ISSUE TITLE
The origin of word hostie

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-puppet-hostie#19]
Hi, 

Just curious, when talking about _"hostie service"_, where is the word _"hostie"_ originated from?

Thanks

**Comment by huan** [comment]
You can find the definition from our wiki at <https://github.com/wechaty/wechaty/wiki/Hostie>

### Hostie /hōsty/

noun
1. a run time who provides the necessary resources (CPU/Memory/Network, etc) for serving bots.

> "a Wechaty hostie"

When we created a Wechaty hostie, it could be one of the following:

1. A Running Wechaty Docker Container
1. A Running Wechaty Electron Application
1. A Running Wechaty in a VPS.
1. etc.

### See Also

* [Wechaty 101: from v0.0 to v0.7](https://blog.chatie.io/wechaty-101-presentation/)

**Comment by suntong** [comment]
Oh, thanks for the explanation. When I was asking where the word "hostie" is originated from, I was thinking that where do you get the idea from. Because when I was searching for the word "hostie", the fist or second hit by google says it is a curse word. 

> When used as a swear word, hostie may also written without the letters "h", "e" or without both letters. It is a french biblical word (the sacramental bread) often...

**Comment by huan** [comment]
Yes, I know that.

It seems that I always pick a name that will be "curse" somewhere... :P

**Comment by suntong** [comment]
K. thanks.
