### ISSUE TITLE
Can not send image message without postfix(.png/.jpg) url.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-hostie#34]
**Example**
```js
const img = FileBox.fromUrl('https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5d0231f2b847d96f9cdfdae1_1587716279293_null')
message.say(img)
```

When `wechaty-puppet-padplus` or `wechaty-puppet-donut` receive the `messageSendFile` request, they will do this operation to get type info:
```js
const type = (file.mimeType && file.mimeType !== 'application/octet-stream')
  ? file.mimeType
  : path.extname(file.name)
```

I found some codes in `wechaty-puppet-hostie`:
```js
const request = new MessageSendFileRequest()
request.setConversationId(conversationId)
request.setFilebox(JSON.stringify(file))
```

> Maybe `JSON.stringify()` will break `fileBox.mimeType`? 

I'm not sure the problem is due to this reason, just a guess.

**Comment by huan** [comment]
It should not break anything.

If it has, then it's a bug.

Please feel free to check the source code in filebox or write an unit test to double confirm it.

**Comment by su-chang** [comment]
This bug is due to package `mime@2.3.1` which `file-box` depend.

```js
mime.getType('https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5d0231f2b847d96f9cdfdae1_1587716279293_null') // it will return null
```

So `fileBox.mimeType` will return null.

I upgrade `mime@next` but in vain.

This url with a bad name make `mime` failed. );

**Comment by su-chang** [comment]
`fileBox.ready()` will resolve this problem.

**Comment by huan** [comment]
Of course, `ready()` should do that.
