### ISSUE TITLE
The FriendshipPayload object missed one important attribute(contactId) in friendshipRawPayload method.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-hostie#36]
We can not auto accept friendship request, due to we can not load contact success when we received one friendship event.

```js
  public async friendshipRawPayload (id: string): Promise<FriendshipPayload> {
    log.verbose('PuppetHostie', 'friendshipRawPayload(%s)', id)

    const request = new FriendshipPayloadRequest()
    request.setId(id)

    const response = await util.promisify(
      this.grpcClient!.friendshipPayload.bind(this.grpcClient)
    )(request)

    const payload: FriendshipPayload = {
      scene    : response.getScene() as number,
      stranger : response.getStranger(),
      ticket    : response.getTicket(),
      type      : response.getType() as number,
    } as any  // FIXME: Huan(202002)

    return payload
  }
```

This method will return a friendship `payload` without `contactId` and `id`.

So we can not make `await this.contact().ready()` right, because no `contactId` in this payload.

```js
  public contact (): Contact {
    if (!this.payload) {
      throw new Error('no payload')
    }

    const contact = this.wechaty.Contact.load(this.payload.contactId)
    return contact
  }
```

In the end, the attributes `id` and `contactId` should add to `FriendshipPayload`, then I think the auto accept friendship request will work right.

**Comment by huan** [comment]
Thank you very much for figuring this bug out and I believe this is the real reason which caused our friendship problem at https://github.com/wechaty/wechaty/issues/1954

**Comment by su-chang** [comment]
Resolved!

**Comment by huan** [comment]
Thank you for the fixing, appreciate it!
