### ISSUE TITLE
[RFC] Support C/S connection with ip and port

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty-puppet-hostie#72]
I would like to raise this topic to discuss about a new feature: support `wechaty-puppet-hostie` client to connect server with `ip` and `port` in options, which will skip the `discoverIp` phase.

## Initiative

We want to setup hostie server with private ip addresses so we can run these servers in private network.

## Proposed solution

We can add two properties to `PuppetOptions` of `wechaty-puppet-hostie`:
* ip
* port

And we can also use env var to set these values:
* WECHATY_PUPPET_HOSTIE_SERVER_IP
* WECHATY_PUPPET_HOSTIE_SERVER_PORT

When we start the `wechaty-puppet-hostie` client, we can check the values are set or not, if not, we go through the `discoverIp` branch to get the ip and port, if the value is set, we will just use this and skip the `discoverIp` process.

**Comment by Jesn** [comment]
god idea !  
Discoverip takes too long

**Comment by windmemory** [comment]
Seems like we can use `endpoint` in `PuppetOptions` to specify the connection endpoint. Code like below:

```ts
const bot = new Wechaty({
  puppet: 'wechaty-puppet-hostie',
  puppetOptions: {
    token: 'my-token',
    endpoint: '127.0.0.1:3000',
  },
})
```
