### ISSUE TITLE
WECHATY_PUPPET_HOSTIE_TOKEN

### ISSUE THREAD

**Issue by tfssweb** [wechaty/wechaty-puppet-hostie#94]
WECHATY_PUPPET_HOSTIE_TOKEN这个在哪获取？启动总是报错：cannot get ip by token, check token

**Comment by huan** [comment]
Please refer to https://github.com/wechaty/wechaty/issues/1986

**Comment by tfssweb** [comment]
> Please refer to [wechaty/wechaty#1986](https://github.com/wechaty/wechaty/issues/1986)
> 
> Here's the FAQ for Wechaty Puppet Service Providers: [wechaty/puppet-service-providers#1](https://github.com/wechaty/puppet-service-providers/issues/1)

好的 谢谢

**Comment by huan** [comment]
You are welcome!

**Comment by tfssweb** [comment]
已解决
