### ISSUE TITLE
基于windows版本的协议发送图片会出现报错?

### ISSUE THREAD

**Issue by nzjcnjzx** [wechaty/wechaty-puppet-hostie#99]
![image](https://user-images.githubusercontent.com/31735124/99029299-1a8dc280-25ad-11eb-8e2f-3e75a597f0a7.png)
请问有人发送成功过吗？

**Comment by nzjcnjzx** [comment]
找到原因了， 原来要引入wechaty的FileBox， 不能引入file-box模块中的FileBox

**Comment by huan** [comment]
Thanks for sharing the solution that you found for the community!

I believe this should be improved in the future.

**Comment by huan** [comment]
This problem should not exist anymore after Wechaty v0.50.6

Thank you very much for this issue and please let me know if you can confirm this problem has been solved in the new version.

**Comment by huan** [comment]
Link to https://github.com/wechaty/wechaty/issues/2090
